word= "harsha"
print(word[0])
print(word[1:])
print(word[-1])
print(word[:3])
print(word[:])
print(word[::1])
print(word[:-1])
print(word[::3])
print(word[::-1])
print(word[1::2])
print(word[::2])
